### ISSUE TITLE
Android KVM not found

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#101]
Creating Android Virtual Devices using `Android AVD Manager` requires Android KVM, which is not installed / configured by default in **AndroidTamer 4**

![screenshot 142](https://cloud.githubusercontent.com/assets/12944530/16608538/7f0ca912-436a-11e6-8aab-02455bb174bb.png)

**Comment by anantshri** [comment]
Please use arm emulator inside virtualbox : https://tools.androidtamer.com/General/running_emulator/

if you want to run intel (x86/x64) emulator you need to run it on base machine https://tools.androidtamer.com/General/repo_configure/ or via VMWare (workstation/Player/Fusion)
