### ISSUE TITLE
Yadd-dumper cant be installed in AndroidTamer4

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#102]
While marking yadd-dumper for installation in Synaptic package manager in AndroidTamer 4, the following error occured stating : **_libc: not installable_**

![screenshot](https://cloud.githubusercontent.com/assets/12944530/16705969/3c66aefa-45b8-11e6-8647-b6f4e73712fe.png)

**Comment by anantshri** [comment]
fix pushed public. dependency was incorrectly named as libc should have been libc6

https://github.com/AndroidTamer/Packaging_Tools/commit/09bd8e8f87af1c08b3a4f20c852b563e94c4e35a
