### ISSUE TITLE
automate-drozer.py

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#117]
https://github.com/interference-security/scripts-tools-shells/blob/master/automate-drozer.py

**Comment by anantshri** [comment]
we are already doing a bunch of these via https://github.com/AndroidTamer/drozer_checks lets see if we can integrate the proper reporting option in it.

**Comment by anantshri** [comment]
now tracked https://github.com/AndroidTamer/drozer_checks/issues/6
