### ISSUE TITLE
Hooker

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#118]
https://github.com/AndroidHooker/hooker

**Comment by anantshri** [comment]
This tool will not work as is, as it relies on substrate which is not being maintained beyond 4.X versions. Hence we need to identify if there is anything which can be used.

I see updates on project last in 6 months so seems some people are still using it, we need to understand is it possible to use it outside of substrate model too.

**Comment by anantshri** [comment]
this is substrate only. hence not adding it here.
