### ISSUE TITLE
ApkInspector

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#133]
I found this interesting repo:
https://github.com/honeynet/apkinspector/

What do you think @anantshri ?

**Comment by anantshri** [comment]
The QT package is a very heavy dependency i will see how we can package this but pushing this in default distro is out of question i suppose. I will ensure its present in repository so anyone can pick and install them.

**Comment by anantshri** [comment]
comments like these https://github.com/honeynet/apkinspector/issues/12 confirms that it will be a hard target. no updates since 2013 i am closing this issue as there is no point adding a near obsolete tool.
