### ISSUE TITLE
keep an eye droidefense

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/Tools_Repository#143]
https://github.com/droidefense/engine

**Comment by 0xbadshah** [comment]
Android Tamer includes malware analysis frameworks..?

**Comment by anantshri** [comment]
yes we do include malware analysis tools.

**Comment by anantshri** [comment]
still coming soon. we will need this issue open for some more time

**Comment by anantshri** [comment]
Closing this. Its been coming soon for far too long now. Once its out we will restart tracking on a fresh issue.
