### ISSUE TITLE
`nikto` not cannot be installed

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#146]
**chandrapal@DebianTestVM:~$** `sudo apt-get install androidtamer-pentesting`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 androidtamer-pentesting : Depends: nikto but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**System Specification:** _Debian GNU/Linux 8_

**Comment by 0xbadshah** [comment]
`nikto` cannot be installed in both Debian 8 Jessie and Debian 8 Minimal OS ( Issue #100 )

**Comment by anantshri** [comment]
Something we need to recheck once we go to Debian 9. We need to ensure all our base packages are easily install able on Debian 9 base. closing this for now. I will add a seperate check in Tamer5 for all these
