### ISSUE TITLE
https://github.com/jakev/CobraDroidBeta

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#182]

**Comment by anantshri** [comment]
This project appears to be dead and deals with a custom emulator image. not sure if spending time on it would make any sense. Please suggest if there is anything in perticular that we should have otherwise there is no point tracking this project.

**Comment by anantshri** [comment]
now tracked in emulator project. https://github.com/AndroidTamer/x86_arm_custom_emulator/issues/6
