### ISSUE TITLE
Tool Addition: SUPER Android analyzer

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#192]
download the binary 

https://github.com/SUPERAndroidAnalyzer/super/releases

dpkg -i .deb file

super -h , should make the tool work in same path

**Comment by anantshri** [comment]
This is interesting. as it already has deb we plan to directly upload the deb in repository, permission requested from owner before taking the action. (not required as license allows us but better to take permission)

**Comment by anantshri** [comment]
seems like super is a used binary / package name in debian https://packages.debian.org/search?keywords=super will check what alterantives are possible before making it available as part of AndroidTamer repo

**Comment by anantshri** [comment]
upstream bug raised: https://github.com/SUPERAndroidAnalyzer/super/issues/104

**Comment by anantshri** [comment]
upstream fixed : https://github.com/AndroidTamer/Tools_Repository/issues/203
