### ISSUE TITLE
Androwarn working fine

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#199]
Follow instructions as below:

https://github.com/maaaaz/androwarn/wiki/Installation

The link wget http://www.chilkatsoft.com/download/chilkat-9.4.0-python-2.6-i686-linux.tar.gz doesnt work instead use 
http://mirror.nienbo.com/chilkat/9.4.0/python/linux/

Untar and copy files _chilkat.so and chilkat.py to androwarn/search/manifest.

It should work fine:

python androwarn.py -i /home/android/Desktop/test.apk -r html -v 3

**Comment by anantshri** [comment]
When we last tried integrating this tool in Android tamer we faced multiple challenges.

https://github.com/AndroidTamer/Tools_Repository/issues/5

Mainly 
1) the tool creates reports within its own directory. 
2) you can't call the tool from a different place. 

that makes this a hard to include tool. We will look into this and if situation changes we will be tracking it on https://github.com/AndroidTamer/Tools_Repository/issues/5

**Comment by pentagramz** [comment]
as described above..the tool runs fine
