### ISSUE TITLE
Burp Should use java 8 if available

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/Tools_Repository#204]
we need to add logic to pick java 8 if available even if not default and if java 8 is not found we use normal java available on system.

**Comment by 0xbadshah** [comment]
What difference does using java 8 make ?

**Comment by anantshri** [comment]
burp has better compatibility with java 8. the newer development work is happening on java 8 so we might be not giving them optimal environment if we use java 7 for burp. 

Also some extensions are java 8 specific like .net beautifier. 

At build environment we already do java switching to compile some stuff properly.
https://github.com/AndroidTamer/Packaging_Tools/blob/381ea93815edb3771d45215bffa0a3d6de112664/Build/smali/build.sh#L19

we need to add a simmilar codeblock in this package launcher to ensure that java 8 is used to launch it. At the same time i suppose keeping java 7 system wide default is still the best option.

**Comment by anantshri** [comment]
Done : https://github.com/AndroidTamer/Packaging_Tools/commit/b36cabf2492be63b0cbe78279cd8cb5037241803
