### ISSUE TITLE
https://github.com/melbfish/tutis

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#254]
https://github.com/melbfish/tutis

**Comment by 0xbadshah** [comment]
There hasnt been any code commits since 3 years. Does the code work now ?

**Comment by pentagramz** [comment]
Didn't checked yet

**Comment by anantshri** [comment]
this doesn't have any functional code. closing the issue for now. If someone found that there is a working code then please reopen it.
