### ISSUE TITLE
Smartphonedumpapps

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#30]
https://code.google.com/archive/p/smartphonesdumbapps/downloads

**Comment by anantshri** [comment]
@pentagramz Is there a github link available google code link doesn't allow much to do done now.

**Comment by 0xbadshah** [comment]
Why cant the project be exported to Github by someone ?

**Comment by anantshri** [comment]
found github export : https://github.com/mluqman31/smartphonesdumbapps

**Comment by anantshri** [comment]
This is massively outdatedcode base i don't see a merit in including this in the distro. Please reopen the issue if anything specifically good found in this list. 
https://github.com/mluqman31/smartphonesdumbapps
