### ISSUE TITLE
android-scripts

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#39]
https://github.com/strazzere/android-scripts

**Comment by anantshri** [comment]
Very focused scripts, if there is anything specific you need from this please open seperate issues for them.

**Comment by anantshri** [comment]
Probably some decoders could be included: https://github.com/strazzere/android-scripts/tree/master/Decoders

**Comment by anantshri** [comment]
https://github.com/strazzere/android-scripts/blob/master/file/java this is interesting

**Comment by anantshri** [comment]
interesting scripts and code but only file/java thing is worth looking at rest all are minor but nothing that we should be jumping to include.
