### ISSUE TITLE
Distributing NDK / SDK / Studio

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/Tools_Repository#48]
at this point we are trying to bundle SDK NDK and Studio in the OVA file itself. However after decompression the total used space by these 3 is 3.9GB out of which 
2.7GB : NDK
0.6 GB : SDK
0.5 GB : Studio

Hence its decided to go ahead with Putting SDK and Studio in this release and then creating 2 installer packages which will basically download the zip file from google servers and unzip and configure them for the users

This will reduce the size of OVA considerably. 

Alternatively we can also bundle the ZIP files which will be of small sizes and should take around 1.5GB total space and an option to decompress them via a installer-script be made available on the desktop.

**Comment by 0xbadshah** [comment]
So Tamer downloads ~ 2.7 GB of data (NDK) after installing them as virtual machines ?

**Comment by anantshri** [comment]
Till i decided about this, I was prepackaging the NDK SDK and Studio in uncompressed format. And that resulted in 6.5 GB of OVA, however i am finding that i have 2-3 options.
1) don't give out NDK at all
2) give out zip file of NDK and a local option to unzip it and configure for the user.
3) third option is where a 700 MB zip is downloaded and is extracted.

So even if we don't ship anything with Tamer we are not asking them to download more than 1GB additional data.

**Comment by 0xbadshah** [comment]
1) I dont think avoiding NDK is good idea.
2) So you mean that you will have a separate zip file of NDK at Tamer website ?
3) Are you using 7z format compression ?

I think having a separate zip (or 7z compressed) file for NDK is better than not having it at all.
I would suggest:
1) Compress the Tamer OVA file without NDK
2) Have separate file which includes NDK and could be downloaded

**Comment by anantshri** [comment]
After bulk of checks, Decision reverted, we are shipping NDK its not adding that much of an overhead on the final build.
