### ISSUE TITLE
Change "Graphical Execution log Viewer" in menu to "Traceview"

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#58]
Traceview can be easily identified than calling it "Graphical Execution log Viewer". Even the command used is: 
`x-terminal-emulator --command "traceview; $SHELL"`

**Comment by anantshri** [comment]
Corrected here : https://github.com/AndroidTamer/androidtamer-menuitems/commit/b46b53edfa06ebd69175d3e6d363596f0b97847d
