### ISSUE TITLE
MobSF Setup Device

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#69]
**Errors:**
- **_[INFO] Getting ADB Location_**
  chmod: changing permissions of ‘/usr/share/MobSF/DynamicAnalyzer/tools/adb/linux/’: Operation not permitted
- **_[INFO] Executing Command - /usr/share/MobSF/DynamicAnalyzer/tools/adb/linux/adb -s 192.168.56.101:5555 shell su -c mount -o rw,remount,rw /system_**

```
su: invalid option -- o

Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -u                            display the multiuser mode and exit
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
```
- **_[INFO] Executing Command - /usr/share/MobSF/DynamicAnalyzer/tools/adb/linux/adb -s 192.168.56.101:5555 shell su -c cp /data/local/tmp/0025aabb.0 /system/etc/security/cacerts/0025aabb.0_**
  Unknown id: /data/local/tmp/0025aabb.0
- **_[INFO] Executing Command - /usr/share/MobSF/DynamicAnalyzer/tools/adb/linux/adb -s 192.168.56.101:5555 install -r /usr/share/MobSF/DynamicAnalyzer/tools/onDevice/DataPusher.apk
  [INFO] Executing Command - /usr/share/MobSF/DynamicAnalyzer/tools/adb/linux/adb -s 192.168.56.101:5555 install -r /usr/share/MobSF/DynamicAnalyzer/tools/onDevice/ScreenCast.apk_**
  Both commands return the same error:
  Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]

**Comment by 0xbadshah** [comment]
Possible solution for the first error 

> **_[INFO] Getting ADB Location_**
> chmod: changing permissions of ‘/usr/share/MobSF/DynamicAnalyzer/tools/adb/linux/’: Operation not permitted

is changing the code on the file `mobsfy.py`. **sudo** should be added infront of chmod

Original:

```
            elif platform.system()=="Linux":
              adb_dir=os.path.join(TOOLSDIR, 'adb/linux/')
              subprocess.call(["chmod", "777", adb_dir])
```

Corrected:

```
            elif platform.system()=="Linux":
              adb_dir=os.path.join(TOOLSDIR, 'adb/linux/')
              subprocess.call(["sudo chmod", "777", adb_dir])
```

**Comment by anantshri** [comment]
I suppose you should use custom binary path inside config/settings.py in home directory. 

https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/138
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/145

**Comment by anantshri** [comment]
I will close this for now. we wll reopen if latest verison has same issues
