### ISSUE TITLE
Andbug font color

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#73]
As the background is white, it is hard to figure out the words. Examples are hardly seen.
Attached image. Change the colour.

![screenshot 125](https://cloud.githubusercontent.com/assets/12944530/15811242/74b61e7a-2bc4-11e6-89c4-547a41674f0b.jpg)

**Comment by anantshri** [comment]
This should be an upstream bug we can't take care of these issues.

**Comment by anantshri** [comment]
upstream issue added: https://github.com/swdunlop/AndBug/issues/26
