### ISSUE TITLE
YADD

### ISSUE THREAD

**Issue by pentagramz** [AndroidTamer/Tools_Repository#82]
https://github.com/ZSShen/YADD

**Comment by anantshri** [comment]
added : https://github.com/AndroidTamer/Packaging_Tools/commit/9fb866d0dd250c158ddff5d1567aab403a852f96

**Comment by anantshri** [comment]
Issues fixed with https://github.com/AndroidTamer/Packaging_Tools/commit/09bd8e8f87af1c08b3a4f20c852b563e94c4e35a
